server:
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      external-dns.alpha.kubernetes.io/hostname: "argocd.cavas.dev.br"
      kubernetes.io/ingress.class: "alb"
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:975050352319:certificate/ad03a490-9bbf-4149-b07e-05ffc596881f
      alb.ingress.kubernetes.io/actions.ssl-redirect: |
        {"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}
    hosts:
      - "argocd.cavas.dev.br"
    path: /
    tls:
      - secretName: "argocd-tls-secret"
        hosts:
          - "argocd.cavas.dev.br"
controller:
  installCRDs: true

# Configuração para DNS
externalDNS:
  enabled: true
  provider: aws
  domainFilters:
    - "cavas.dev.br"
  aws:
    accessKeyId: "${var.aws_access_key_id}"
    secretAccessKey: "${var.aws_secret_access_key}"
    region: "us-east-1"
  policy: "sync"
  interval: "1m"