controller:
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    externalTrafficPolicy: Local

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

defaultBackend:
  enabled: false
